Added implementation and test cases for checkSubTree problem
LorenzNickel/java-fundamentals pull request #13
Opened 2020-10-06 22:22 UTC by p-nath

2020-10-07 15:04 UTC, LorenzNickel requested changes
Hey, thanks a lot for your contribution 🥇 

I have some suggestions for minor things which should be changed before this PR can be merged.

Feel free to push an additional commit addressing my feedback to your fork (or apply the changes within the pushed commits if you want), then I'll be happy to approve and merge your PR.

Hint: You can try to compile the project locally to see if you comply with the formatting rules of this repository or push here and have a look at the CI. In general we are following the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) for which you can also download auto-formatting presets for most IDEs somewhere on the internet if you want. I'll create a CONTRIBUTING.md file shorty to make this more obvious for other contributors in the future.

2020-10-07 15:04 UTC, LorenzNickel commented on src/main/java/problems/checkSubTree/resources/TreeNode.java
> +  }
Please add an empty line before every constructor to make the build pass by complying with the formatting guidelines:

```
public class TreeNode {

  public int val;
  public TreeNode left;
  public TreeNode right;

  public TreeNode() {}

  public TreeNode(int val) {
    this.val = val;
    this.left = null;
    this.right = null;
  }

  TreeNode(int val, TreeNode left, TreeNode right) {
    this.val = val;
    this.left = left;
    this.right = right;
  }
}
```

Also I'm not sure about the visibility of the third constructor, is there any reason why it's not public like the others?

2020-10-10 07:44 UTC, p-nath commented on src/main/java/problems/checkSubTree/README.md
> +Time complexity of recursively traversing the tree 's' is O(m) is 'm' be the total number nodes in it
Thanks for the heads up! I forgot to do the maven compile. Will do a new PR with the changes.

2020-10-10 14:00 UTC, LorenzNickel approved these changes

2020-10-10 14:00 UTC, merged